export const platform = { title: "platform", querys: ["PC", "Browser"] };
export const category = {
  title: "category",
  querys: [
    "MMO",
    "MMORPG",
    "Shooter",
    "Strategy",
    "Moba",
    "Card",
    "Racing",
    "Sports",
    "Social",
    "Fighting",
    "MMOFPS",
    "Action RPG",
    "Sandbox",
    "Open World",
    "Survival",
    "Battle Royale",
    "MMOTPS",
    "Anime",
    "PvP",
    "PvE",
    "Pixel",
    "MMORTS",
    "Fantasy",
    "Sci-Fi",
    "Action",
    "Voxel",
    "Zombie",
    "Turn-Based",
    "First Person",
    "Third Person",
    "Top-Down",
    "3D",
    "2D",
    "Tank",
    "Space",
    "Sailing",
    "Side Scroller",
    "Superhero",
    "Permadeath",
  ],
};

export const sort_by = {
  title: "sort_by",
  querys: ["Relevance", "Popularity", "Release-date", "Alphabetical"],
};
